### PR TITLE
#23 - upgrade react and redux in exercises

### LINKED ISSUE #23: Upgrade React and Redux
If you continue in the same exercise and install latest redux you get a strange error that can be solved by upgrading react to the latest.

Update react redux to latest

### PR DESCRIPTION
**Pull request by littlewhywhat**
PR adds/not resolves warnings:

in console
```
react-dom.development.js:88 Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

* Move data fetching code or side effects to componentDidUpdate.
* If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
* Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.

Please update the following components: Connect(Header), Connect(UsersList), Provider
```

in builds with salsita libs:
```
warning " > @salsita/react-core@1.0.0" has incorrect peer dependency "redux@^3.7.2".
warning "@salsita/react-core > redux-router5@5.5.0" has unmet peer dependency "router5@^5.0.0 || ^6.0.0".
warning "@salsita/react-core > redux-router5 > router5-transition-path@5.3.0" has unmet peer dependency "router5@^5.0.0 || ^6.0.0".
warning "@salsita/react-api > @salsita/react-core > redux-router5@5.5.0" has unmet peer dependency "router5@^5.0.0 || ^6.0.0".
```
But functionality is not affected

closes #23

### CODE REVIEW

**Comment by novellizator** [comment]
Do we need to change this in every exercise?

**Comment by littlewhywhat** [comment]
> Do we need to change this in every exercise?

@novellizator we can change it only in the ones where we don't have redux in package.json I guess :) would it be preferred?

**Comment by novellizator** [comment]
Ideally I'd have one global package.json for all exercises in the /exercises folder (just pick one from the latest exercise). Would you able to configure it like that?

**Comment by littlewhywhat** [comment]
@novellizator good idea - I moved all dependencies in one package.json and it seems that running react-scripts from child folders works without any additional configuration. To avoid using prefixes "../node_modules/.bin/" for each executable in child, I used link-parent-bin module - it creates .bin folder in each child project with links to original bins

**Pull request merged**
